name: Go Build and Release

on:
  push:
    tags:
      - "v*"  # 只有推送 v 开头的 tag 时才触发整个工作流

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 允许发布 Release
    steps:
      # 检出代码（必须包含 fetch-depth: 0 才能读取 tag）
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 设置 Go 环境
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      # 编译
      - name: Build
        run: go build -v -o main ./.

      # 发布到 GitHub Release（自动使用触发的 tag）
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: main          # 上传编译好的二进制文件
          tag_name: ${{ github.ref_name }}  # 使用触发的 tag
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}