name: Go Build and Release

on:
  push:
    tags:
      - "v*"  # 仅 v 开头的 tag 触发

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        platform:
          - { os: linux, goos: linux, goarch: amd64, suffix: "" }
          - { os: linux, goos: linux, goarch: arm64, suffix: "-arm64" }
          - { os: windows, goos: windows, goarch: amd64, suffix: ".exe" }
          - { os: macos, goos: darwin, goarch: amd64, suffix: "-darwin" }
          - { os: macos, goos: darwin, goarch: arm64, suffix: "-darwin-arm64" }
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Build
        env:
          GOOS: ${{ matrix.platform.goos }}
          GOARCH: ${{ matrix.platform.goarch }}
          CGO_ENABLED: 0  # 静态编译
        run: |
          output_name="main-${{ matrix.platform.goos }}-${{ matrix.platform.goarch }}${{ matrix.platform.suffix }}"
          go build -v -o $output_name .
          echo "BINARY_NAME=$output_name" >> $GITHUB_ENV

      - name: Upload Artifact
        uses: actions/upload-artifact@v4  # 关键修复：升级到 v4
        with:
          name: ${{ env.BINARY_NAME }}
          path: ${{ env.BINARY_NAME }}

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4  # 同步升级到 v4
        with:
          path: artifacts
          merge-multiple: true  # 关键修复：合并文件

      - name: Verify Files
        run: ls -R artifacts  # 调试用

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/main-darwin-amd64-darwin
            artifacts/main-darwin-arm64-darwin-arm64
            artifacts/main-linux-amd64
            artifacts/main-linux-arm64-arm64
            artifacts/main-windows-amd64.exe
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}